// src/data/comarcas.js

import type { ComarcaInfo } from "@/@types";

export const comarcasInfo: ComarcaInfo[] = [
  { nome: "APARECIDA", rota: "08", endereco: "TJ" },
  { nome: "ARARAQUARA", rota: "15", endereco: "TJ" },
  { nome: "ARUJÁ", rota: "06", endereco: "TJ" },
  { nome: "ASSIS", rota: "16", endereco: "TJ" },
  { nome: "ATIBAIA", rota: "14", endereco: "TJ" },
  { nome: "AVARÉ", rota: "16", endereco: "TJ" },
  { nome: "AMERICANA", rota: "02", endereco: "TJ" },
  { nome: "ARTUR NOGUEIRA", rota: "13", endereco: "TJ" },
  { nome: "BARRETOS", rota: "15", endereco: "TJ" },
  { nome: "BARUERI", rota: "04", endereco: "TJ" },
  { nome: "BAURU", rota: "16", endereco: "TJ" },
  { nome: "BOTUCATU", rota: "16", endereco: "TJ" },
  { nome: "BRAGANÇA PTA", rota: "14", endereco: "TJ" },
  { nome: "BRAS CUBAS", rota: "06", endereco: "TJ" },
  { nome: "BRIGADEIRO DIREITO PÚBLICO", rota: "09", endereco: "2 º Instancia - Praça Almeida Júnior, nº 72" },
  { nome: "BRIGADEIRO RECURSO ESPECIAL", rota: "09", endereco: "2 º Instancia - Av Brig Luis Antonio, 849" },
  { nome: "BUTANTÃ", rota: "11", endereco: "Av. Corifeu de Azevedo Marques, 184 -Butantã" },
  { nome: "CAÇAPAVA", rota: "08", endereco: "TJ" },
  { nome: "CAIEIRAS", rota: "14", endereco: "TJ" },
  { nome: "CAJAMAR", rota: "04", endereco: "TJ" },
  { nome: "CAMPINAS", rota: "13", endereco: "TJ" },
  { nome: "CAMPO LIMPO PTA.", rota: "14", endereco: "TJ" },
  { nome: "CANDIDO MOTA", rota: "16", endereco: "TJ" },
  { nome: "CARAPICUIBA", rota: "04", endereco: "TJ" },
  { nome: "CATANDUVA", rota: "15", endereco: "TJ" },
  { nome: "CENTRO CONSOLAÇÃO 1", rota: "09", endereco: "Prédio Praça Patriarca, Rua Direita, 250 - 14º andar" },
  { nome: "CENTRO CONSOLAÇÃO 2", rota: "09", endereco: "Rua Bela Cintra , 151 - Consolação" },
  { nome: "CENTRO CONSOLAÇÃO 3", rota: "09", endereco: "Rua da Consolação ,1483 - Consolação" },
  { nome: "CENTRO CONSOLAÇÃO 4", rota: "09", endereco: "Rua Direita , 250 - Sé (Patriarca)" },
  { nome: "COMPLEXO PATRIARCA", rota: "09", endereco: "HELY LOPES MEIRELLES" },
  { nome: "COMPLEXO VERGUEIRO 1", rota: "09", endereco: "Praça Almeida Junior, Nº 35 - Liberdade" },
  { nome: "COMPLEXO VERGUEIRO 2", rota: "09", endereco: "Rua Vergueiro , Nº 835" },
  { nome: "COORDENADORIA DE ARQUIVOS", rota: "RESERVA TÉCNICA", endereco: "RUA DIREITA, 250 - 11° ANDAR" },
  { nome: "COTIA", rota: "07", endereco: "TJ" },
  { nome: "CUBATÃO", rota: "01", endereco: "TJ" },
  { nome: "DEPRE - COMPLEXO IPIRANGA", rota: "09", endereco: "HELY LOPES MEIRELLES" },
  { nome: "DIADEMA", rota: "05", endereco: "TJ" },
  { nome: "DIRETORIA PRIVADO", rota: "09", endereco: "TJ" },
  { nome: "FERRAZ DE VASCONCELOS", rota: "06", endereco: "TJ" },
  { nome: "FORUM DE SANTANA", rota: "10", endereco: "TJ" },
  { nome: "FORUM JOÃO MENDES 1", rota: "09", endereco: "TJ" },
  { nome: "FORUM JOÃO MENDES 2", rota: "09", endereco: "TJ" },
  { nome: "FORO REGIONAL DE PINHEIROS", rota: "11", endereco: "TJ" },
  { nome: "FRANCA", rota: "15", endereco: "TJ" },
  { nome: "FRANCISCO MORATO", rota: "14", endereco: "TJ" },
  { nome: "FRANCO DA ROCHA", rota: "14", endereco: "TJ" },
  { nome: "GARÇA", rota: "16", endereco: "TJ" },
  { nome: "GUARATINGUETÁ", rota: "08", endereco: "TJ" },
  { nome: "GUARUJA", rota: "01", endereco: "TJ" },
  { nome: "GUARULHOS", rota: "06", endereco: "TJ" },
  { nome: "HORTOLÂNDIA", rota: "02", endereco: "TJ" },
  { nome: "INDAIATUBA", rota: "13", endereco: "TJ" },
  { nome: "IPIRANGA", rota: "11", endereco: "TJ" },
  { nome: "IPIRANGA 2", rota: "09", endereco: "2 º Instancia - Rua Agostinho Gomes, 1225" },
  { nome: "ITANHAÉM", rota: "03", endereco: "TJ" },
  { nome: "ITAPEVI", rota: "04", endereco: "TJ" },
  { nome: "ITAPETININGA", rota: "07", endereco: "TJ" },
  { nome: "ITAQUAQUECETUBA", rota: "06", endereco: "TJ" },
  { nome: "ITAQUERA", rota: "12", endereco: "TJ" },
  { nome: "ITATIBA", rota: "14", endereco: "TJ" },
  { nome: "ITU", rota: "13", endereco: "TJ" },
  { nome: "JABAQUARA 2", rota: "11", endereco: "CIVEL" },
  { nome: "JACAREÍ", rota: "08", endereco: "TJ" },
  { nome: "JANDIRA", rota: "04", endereco: "TJ" },
  { nome: "JARINU", rota: "14", endereco: "TJ" },
  { nome: "JAU", rota: "16", endereco: "TJ" },
  { nome: "JOÃO MENDES / CPP", rota: "09", endereco: "Comissão Proc. Permantente. Vara 02° Instância" },
  { nome: "JUNDIAÍ", rota: "14", endereco: "TJ" },
  { nome: "LAPA", rota: "10", endereco: "TJ" },
  { nome: "LIMEIRA", rota: "02", endereco: "TJ" },
  { nome: "MAIRINQUE", rota: "07", endereco: "TJ" },
  { nome: "MAIRIPORÃ", rota: "14", endereco: "TJ" },
  { nome: "MARILIA", rota: "16", endereco: "TJ" },
  { nome: "MARIO GUIMARÃES", rota: "10", endereco: "TJ" },
  { nome: "MATÃO", rota: "15", endereco: "TJ" },
  { nome: "MAUÁ", rota: "05", endereco: "TJ" },
  { nome: "MOGI DAS CRUZES", rota: "06", endereco: "TJ" },
  { nome: "MONGAGUÁ", rota: "03", endereco: "TJ" },
  { nome: "NOVA ODESSA", rota: "02", endereco: "TJ" },
  { nome: "OLIMPIA", rota: "15", endereco: "TJ" },
  { nome: "OSASCO", rota: "04", endereco: "TJ" },
  { nome: "OURINHOS", rota: "16", endereco: "TJ" },
  { nome: "PALACIO DA JUSTIÇA", rota: "09", endereco: "2 º Instancia - Praça da Sé , S/N" },
  { nome: "PALACIO DA JUSTIÇA 2", rota: "9", endereco: "2 º Instancia - Rua da Glória , 459" },
  { nome: "PALMITAL", rota: "16", endereco: "TJ" },
  { nome: "PARAGUAÇU PTA", rota: "16", endereco: "TJ" },
  { nome: "PATIO DO COLEGIO", rota: "09", endereco: "2 º Instancia - Patio do Colegio , 73" },
  { nome: "PEDRO LESSA", rota: "09", endereco: "TJ" },
  { nome: "PENHA DE FRANÇA 2", rota: "12", endereco: "TJ" },
  { nome: "PERUÍBE", rota: "03", endereco: "TJ" },
  { nome: "PINDAMONHANGABA", rota: "08", endereco: "TJ" },
  { nome: "PIRACICABA", rota: "02", endereco: "TJ" },
  { nome: "PIRATININGA(MÁRIO GUIMARÃES)", rota: "10", endereco: "TJ" },
  { nome: "POÁ", rota: "06", endereco: "TJ" },
  { nome: "PORTO FELIZ", rota: "07", endereco: "TJ" },
  { nome: "PRAIA GRANDE", rota: "03", endereco: "TJ" },
  { nome: "PREDIO ADM BRIGADEIRO 1", rota: "10", endereco: "Decrim 01 - Barra Funda" },
  { nome: "PREDIO ADM BRIGADEIRO 2", rota: "11", endereco: "Jabaquara" },
  { nome: "PREDIO ADM BRIGADEIRO 3", rota: "09", endereco: "HELY LOPES MEIRELLES" },
  { nome: "RIBEIRÃO PIRES", rota: "05", endereco: "TJ" },
  { nome: "RIBEIRÃO PRETO", rota: "15", endereco: "TJ" },
  { nome: "RIO CLARO", rota: "02", endereco: "TJ" },
  { nome: "ROSEIRA", rota: "08", endereco: "TJ" },
  { nome: "RUA DA GLÓRIA", rota: "09", endereco: "2ª Instancia - Rua da Glória , 459" },
  { nome: "SALA CATALOGAÇÃO", rota: "SPI/GDC JAGUARÉ", endereco: "CATALOGAÇÃO TJ" },
  { nome: "SALTO", rota: "13", endereco: "TJ" },
  { nome: "SANTA BARBARA D' OESTE", rota: "02", endereco: "TJ" },
  { nome: "SANTANA DE PARNAIBA", rota: "04", endereco: "TJ" },
  { nome: "SANTO ANDRÉ", rota: "05", endereco: "TJ" },
  { nome: "SANTO AMARO 1", rota: "11", endereco: "Crime" },
  { nome: "SANTO AMARO 2", rota: "11", endereco: "Civel" },
  { nome: "SANTOS", rota: "01", endereco: "TJ" },
  { nome: "SÃO BERNARDO DO CAMPO", rota: "05", endereco: "TJ" },
  { nome: "SÃO CAETANO DO SUL", rota: "05", endereco: "TJ" },
  { nome: "SÃO CARLOS", rota: "02", endereco: "TJ" },
  { nome: "SÃO JOSE DOS CAMPOS", rota: "08", endereco: "TJ" },
  { nome: "SÃO JOSÉ DO RIO PRETO", rota: "15", endereco: "TJ" },
  { nome: "SÃO MIGUEL", rota: "12", endereco: "TJ" },
  { nome: "SÃO ROQUE", rota: "07", endereco: "TJ" },
  { nome: "SÃO VICENTE", rota: "03", endereco: "TJ" },
  { nome: "SOROCABA", rota: "07", endereco: "TJ" },
  { nome: "SUMARÉ", rota: "02", endereco: "TJ" },
  { nome: "SUZANO", rota: "06", endereco: "TJ" },
  { nome: "TABOÃO DA SERRA", rota: "05", endereco: "TJ" },
  { nome: "TATUAPE", rota: "12", endereco: "TJ" },
  { nome: "TATUÍ", rota: "07", endereco: "TJ" },
  { nome: "TAUBATÉ", rota: "08", endereco: "TJ" },
  { nome: "TREMEMBÉ", rota: "08", endereco: "TJ" },
  { nome: "TRIBUNAL DE ALÇADAS CR", rota: "09", endereco: "TJ" },
  { nome: "VALINHOS", rota: "13", endereco: "TJ" },
  { nome: "VARGEM GRANDE PTA.", rota: "07", endereco: "TJ" },
  { nome: "VARZEA PTA.", rota: "14", endereco: "TJ" },
  { nome: "VICENTE DE CARVALHO", rota: "01", endereco: "TJ" },
  { nome: "VILA MIMOSA", rota: "13", endereco: "TJ" },
  { nome: "VILA PRUDENTE 1", rota: "12", endereco: "TJ" },
  { nome: "VINHEDO", rota: "13", endereco: "TJ" },
  { nome: "VOTORANTIM", rota: "07", endereco: "TJ" },
  // A comarca 'ITAJOBI' foi omitida por não ter uma rota definida na sua lista.
  // Se quiser incluí-la, precisamos definir uma rota para ela.
];